// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hinkgrvzhrfrbczxxbis.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhpbmtncnZ6aHJmcmJjenh4YmlzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2NzEwMjYsImV4cCI6MjA2MjI0NzAyNn0.ldhS8gYAUF_lGvdJJwOPh4hIqe7IVKaEUREggaPSHX0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);